#!/bin/sh

set -e
set -x

# XXX hardcoded architecture
export LD_LIBRARY_PATH="$SNAP_APP_PATH/usr/lib/x86_64-linux-gnu/NetworkManager${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PATH="$SNAP_APP_PATH/usr/sbin${PATH:+:PATH}"

# TODO drop DEBUG
NetworkManager.patched \
    --state-file=$SNAP_APP_DATA_PATH/NetworkManager.state \
    --config-dir=$SNAP_APP_PATH/etc/NetworkManager \
    --config=$SNAP_APP_PATH/etc/NetworkManager/NetworkManager.conf \
    --log-level=DEBUG \
    --no-daemon \
    "$@"

