name: network-manager
version: 1.2.2-6
summary: Network management framework
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN serivces.
  Please find the source code at https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/network-manager
confinement: strict
grade: stable

slots:
  service: network-manager

plugs:
  nmcli: network-manager

apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [nmcli]
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots: [service]
    plugs: [modem-manager, ppp, network-setup-observe]

parts:
  networkmanager-common:
    plugin: copy
    files:
      bin/networkmanager: bin/networkmanager
      conf/NetworkManager.conf: etc/NetworkManager/NetworkManager.conf
      data/copyright: usr/share/doc/network-manager/copyright

  networkmanager:
    plugin: autotools

    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/network-manager
    source-type: git
    source-branch: network-manager/xenial/1.2.2

    build-packages:
      - intltool
      - gtk-doc-tools
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libiw-dev
      - libglib2.0-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - libnss3-dev
      - libgnutls28-dev
      - libgcrypt11-dev
      - uuid-dev
      - systemd
      - libsystemd-dev
      - libudev-dev
      - libgudev-1.0-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - dbus-test-runner
      - isc-dhcp-client
      - python-dbus
      - python-gi
      - iptables
      - ppp-dev

    # We stage everything here we need for build and runtime
    stage-packages:
      - iputils-arping
      - iw
      - libc6
      - libdbus-1-3
      - libdbus-glib-1-2
      - libgcrypt20
      - libglib2.0-0
      - libgudev-1.0-0
      - libiw-dev
      - libmbim-glib4
      - libndp0
      - libnl-3-200
      - libnl-3-dev
      - libnl-genl-3-200
      - libnl-route-3-200
      - libpam-systemd
      - libreadline6
      - libsystemd0
      - libuuid1
      - lsb-base
      - uuid-dev
      - wireless-tools

    configflags:
      # Disable all features we don't want enabled as we're not
      # supporting them (yet).
      - --prefix=/usr
      - --libdir=/usr/lib
      - --libexecdir=/usr/lib/NetworkManager
      - --disable-qt
      - --disable-teamdctl
      - --disable-polkit
      - --disable-vala
      - --disable-config-plugin-ibft
      - --with-dhcpcd=no
      - --with-dhclient=no
      - --with-dnsmasq=no
      - --with-systemd-journal=no
      # Removes dependency on libicudata which weights 25M. Also libsoup
      # is only used to verify a domain in the DNS resolve process has a
      # valid format and to check if a valid internet connection is available.
      - --with-libsoup=no
      # We want to support ModemManager
      - --with-modem-manager-1=yes

    # Filter files pulled in by stage-packages so they aren't
    # included in the final snap. We only need them to build
    # NetworkManager. All runtime dependencies are pulled in with
    # the rdepends part below. The only left items specified
    # here are the results of the network manager build.
    filesets:
      binaries:
        - usr/bin/nmcli
        - usr/lib/*/NetworkManager
        - usr/lib/pppd/2.4.5/nm-pppd-plugin.so
        - usr/lib/NetworkManager
        - usr/sbin/NetworkManager
        - usr/lib/*/libnm-*
      configs:
        - etc/NetworkManager/*
      docs:
        - usr/share/doc
      rdepends:
        - lib64/*
        - lib/*/
        - usr/lib/*
      unwanted:
        # We don't want anything in usr/share but the doc folder
        # to carry all copyright information
        - -usr/share/bash-completion
        - -usr/share/bug
        - -usr/share/dbus-1
        - -usr/share/gir-1.0
        - -usr/share/glib-2.0
        - -usr/share/gtk-doc
        - -usr/share/lintian
        - -usr/share/locale
        - -usr/share/man
        - -usr/share/pam-configs
        - -usr/share/polkit-1
        - -usr/share/upstart

        # We don't use dhclient so we don't need this helper
        - -usr/lib/NetworkManager/nm-dhcp-helper
        # Things we don't support yet and don't have to ship
        - -usr/lib/NetworkManager/libnm-device-plugin-adsl.so
        - -usr/lib/NetworkManager/libnm-device-plugin-bluetooth.so
        - -usr/lib/NetworkManager/libnm-settings-plugin-ibft.so

        # Unwanted content coming from the stage debian packages
        - -etc/
        # Contains many libraries which are already present in usr/lib/
        - -lib/
        - -usr/include/
        - -usr/etc
        - -usr/sbin/invoke-rc.d
        - -usr/sbin/service
        - -usr/sbin/update-rc.d
        - -usr/lib/dbus-1.0/
        - -usr/lib/tmpfiles.d/
        - -usr/lib/*/pkgconfig
        - -usr/lib/pkgconfig
        - -usr/lib/gcc/
        - -usr/lib/*/gconv/
        - -usr/lib/girepository-1.0/
        - -usr/lib/systemd/
        - -usr/lib/udev/
        - -usr/lib/*.a
        - -usr/lib/*/*.a
        - -usr/lib/*.la
        - -usr/lib/*/*.la
        - -usr/lib/*/*.o
        - -usr/lib/*/systemd-shim
        - -usr/lib/*/systemd-shim-cgroup-release-agent
    snap:
      - $binaries
      - $configs
      - $docs
      - $rdepends
      - $unwanted

