name: network-manager
vendor: Loïc Minier <loic.minier@ubuntu.com>
version: 1.0
type: framework
architecture:
 - amd64
services:
  networkmanager-service:
    description: Network manager
    start: bin/networkmanager
    security-template: unconfined
    bus-name: org.freedesktop.NetworkManager
binaries:
  nmcli:
    exec: usr/bin/nmcli
summary: Network management based on NeworkManager and ModemManager
description: Network management of wired ethernet, WiFi and mobile data connection based on NetworkManager and ModemManager
icon: icon.svg

parts:
  ubuntu-deps:
    # noop to pull packages
    type: copy
    files: []
    stage-packages:
      - network-manager
  symlink-hacks:
    type: make-project
    source: .
    after: [ubuntu-deps]
  wrapper:
    type: copy
    files:
      networkmanager: bin/networkmanager
