name: network-manager
version: 1.1.94-1
type: app
summary: Network management based on NeworkManager
description: Network management of wired ethernet and WiFi based on NetworkManager
icon: icon.svg

apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [unconfined]
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs: [unconfined]
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs: [unconfined]
  NetworkManager:
    command: bin/networkmanager
    daemon: simple
    plugs: [unconfined]
  dnsmasq:
    command: bin/dnsmasq
    daemon: simple
    plugs: [unconfined]

plugs:
  unconfined:
    interface: old-security
    security-template: unconfined

parts:
  networkmanager-common:
    plugin: copy
    files:
      bin/networkmanager: bin/networkmanager
      bin/dnsmasq: bin/dnsmasq
      conf/NetworkManager.conf: etc/NetworkManager/NetworkManager.conf
      conf/dnsmasq-dbus.conf: conf/dnsmasq-dbus.conf

  networkmanager:
    plugin: autotools

    source: https://download.gnome.org/sources/NetworkManager/1.1/NetworkManager-1.1.94.tar.xz

    # NOTE: Force autogen to be executed again even if the tarball already
    # comes with a configure script but that links against aclocal-1.13
    # which we don't profile anymore and will cause the build to fail.
    force-autogen: true

    build-packages:
      - intltool
      - gtk-doc-tools
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libiw-dev
      - libglib2.0-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - libgnutls28-dev
      - libgcrypt11-dev
      - uuid-dev
      - systemd
      - libsystemd-dev
      - libudev-dev
      - libgudev-1.0-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - libsoup2.4-dev
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - dbus-test-runner
      - isc-dhcp-client
      - python-dbus
      - python-gi

    # We stage everything here we need for build and runtime
    stage-packages:
      - init-system-helpers
      - iputils-arping
      - isc-dhcp-client
      - iw
      - libc6
      - libdbus-1-3
      - libdbus-glib-1-2
      - libgcrypt20
      - libglib2.0-0
      - libgudev-1.0-0
      - libiw-dev
      - libmbim-glib4
      - libndp0
      - libnewt0.52
      - libnl-3-200
      - libnl-3-dev
      - libnl-genl-3-200
      - libnl-route-3-200
      - libpam-systemd
      - libreadline6
      - libsoup2.4-1
      - libsystemd0
      - libuuid1
      - lsb-base
      - uuid-dev
      - wireless-tools

    configflags:
      # Disable all features we don't want enabled as we're not
      # supporting them (yet).
      - --prefix=/usr
      - --libexecdir=/usr/lib
      - --disable-qt
      - --disable-teamdctl
      - --disable-polkit
      - --disable-vala
      - --disable-ppp
      - --with-dhcpcd=no
      - --with-dhclient=no
      - --with-dnsmasq=no
      - --with-modem-manager-1=no
