name: network-manager
vendor: Loïc Minier <loic.minier@ubuntu.com>
version: 1.0
type: framework
architecture:
 - amd64
services:
  networkmanager:
    description: Network manager
    start: bin/networkmanager
    security-template: unconfined
    bus-name: org.freedesktop.NetworkManager
binaries:
  nmcli:
    exec: usr/bin/nmcli
    security-template: unconfined
summary: Network management based on NeworkManager and ModemManager
description: Network management of wired ethernet, WiFi and mobile data connection based on NetworkManager and ModemManager
icon: icon.svg

parts:
  network-manager:
    type: x-custom
    after: [dependencies]
    custom-cmds:
      - wget https://launchpad.net/~awe/+archive/ubuntu/ppa/+files/network-manager_1.0.4-0ubuntu4~awe9_amd64.deb
      - dpkg-deb -x network-manager*_amd64.deb $SNAPCRAFT_PART_INSTALL_DIR
  libnm-util:
    type: x-custom
    after: [dependencies]
    custom-cmds:
      - wget https://launchpad.net/~awe/+archive/ubuntu/ppa/+files/libnm-util2_1.0.4-0ubuntu4~awe9_amd64.deb
      - dpkg-deb -x libnm-util*_amd64.deb $SNAPCRAFT_PART_INSTALL_DIR
  dependencies:
    # noop to pull packages
    type: copy
    files: []
    stage-packages:
      # package list generated manually by looking at the output of:
      # $ apt-cache showpkg network-manager
      - adduser
      - libc6
      - libdbus-1-3
      - libdbus-glib-1-2
      - libgcrypt20
      - libglib2.0-0
      - libgnutls-deb0-28
      - libgudev-1.0-0
      - libmm-glib0
      - libndp0
      - libnewt0.52
      - libnl-3-200
      - libnl-genl-3-200
      - libnl-route-3-200
      - libpolkit-agent-1-0
      - libpolkit-gobject-1-0
      - libreadline6
      - libsoup2.4-1
      - libsystemd0
      - libuuid1
      - init-system-helpers
      - lsb-base
      - dnsmasq-base
      - udev
      - isc-dhcp-client
      - libpam-systemd
      - policykit-1
